//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesForceNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Payments = new HashSet<Payment>();
            this.VanOrderProducts = new HashSet<VanOrderProduct>();
        }
    
        public int Id { get; set; }
        public string Date { get; set; }
        public string Remarks { get; set; }
        public string DeliveryDate { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> OutletId { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
    
        public virtual Outlet Outlet { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VanOrderProduct> VanOrderProducts { get; set; }
    }
}
